// <auto-generated />
using System;
using Freight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreightDbContext))]
    [Migration("20260820201339_SplitComplianceStateAndRouteProgressIntoOwnTables")]
    partial class SplitComplianceStateAndRouteProgressIntoOwnTables
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freight.Domain.Fleet.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HazmatCertified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TruckName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TruckSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TruckingCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TruckingCompanies", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("ActualPickupAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("OfferDeadline")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("RequiredTruckType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TruckingCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.HasIndex("TruckingCompanyId");

                    b.ToTable("Shipments", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shippers", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.Driver", b =>
                {
                    b.OwnsOne("Freight.Domain.Tracking.DriverComplianceState", "ComplianceState", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("AwaitingSecondBreakBlock")
                                .HasColumnType("boolean")
                                .HasColumnName("ComplianceState_AwaitingSecondBreakBlock");

                            b1.Property<bool>("AwaitingSecondDailyRestBlock")
                                .HasColumnType("boolean")
                                .HasColumnName("ComplianceState_AwaitingSecondDailyRestBlock");

                            b1.Property<int>("ContinuousDrivingMinutesSinceBreak")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_ContinuousDrivingMinutesSinceBreak");

                            b1.Property<string>("CurrentActivity")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("ComplianceState_CurrentActivity");

                            b1.Property<int>("DailyDrivingMinutesToday")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_DailyDrivingMinutesToday");

                            b1.Property<int>("ExtendedDaysUsedThisWeek")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_ExtendedDaysUsedThisWeek");

                            b1.Property<bool>("IsTodayExtended")
                                .HasColumnType("boolean")
                                .HasColumnName("ComplianceState_IsTodayExtended");

                            b1.Property<DateTime>("LastEvaluatedSimulatedTime")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ComplianceState_LastEvaluatedSimulatedTime");

                            b1.Property<int>("MinutesRemainingInCurrentActivity")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_MinutesRemainingInCurrentActivity");

                            b1.Property<int>("ReducedDailyRestsUsedSinceWeeklyRest")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_ReducedDailyRestsUsedSinceWeeklyRest");

                            b1.Property<int>("WeeklyDrivingMinutesPriorWeek")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_WeeklyDrivingMinutesPriorWeek");

                            b1.Property<int>("WeeklyDrivingMinutesThisWeek")
                                .HasColumnType("integer")
                                .HasColumnName("ComplianceState_WeeklyDrivingMinutesThisWeek");

                            b1.HasKey("DriverId");

                            b1.ToTable("DriverComplianceStates", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.DrivingRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BreakRule")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BreakRule");

                            b1.Property<string>("DailyRestRule")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DailyRestRule");

                            b1.Property<bool>("ExtendDailyDrivingWhenEligible")
                                .HasColumnType("boolean")
                                .HasColumnName("ExtendDailyDrivingWhenEligible");

                            b1.Property<string>("WeeklyRestRule")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("WeeklyRestRule");

                            b1.HasKey("DriverId");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("ComplianceState");

                    b.Navigation("Rules")
                        .IsRequired();
                });

            modelBuilder.Entity("Freight.Domain.Fleet.Truck", b =>
                {
                    b.OwnsOne("Freight.Domain.Fleet.DriverAssignment", "DriverAssignment", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ActiveDriverId")
                                .HasColumnType("uuid")
                                .HasColumnName("ActiveDriverId");

                            b1.Property<string>("ConfigurationType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DriverConfigurationType");

                            b1.Property<Guid>("PrimaryDriverId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SecondaryDriverId")
                                .HasColumnType("uuid");

                            b1.HasKey("TruckId");

                            b1.HasIndex("PrimaryDriverId");

                            b1.HasIndex("SecondaryDriverId");

                            b1.ToTable("Trucks");

                            b1.HasOne("Freight.Domain.Fleet.Driver", "PrimaryDriver")
                                .WithMany()
                                .HasForeignKey("PrimaryDriverId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Freight.Domain.Fleet.Driver", "SecondaryDriver")
                                .WithMany()
                                .HasForeignKey("SecondaryDriverId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("TruckId");

                            b1.Navigation("PrimaryDriver");

                            b1.Navigation("SecondaryDriver");
                        });

                    b.OwnsMany("Freight.Domain.Fleet.Stop", "Stops", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpectedArrivalTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<int>("Sequence")
                                .HasColumnType("integer");

                            b1.Property<Guid?>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("TruckingCompanyId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TruckId");

                            b1.ToTable("TruckRouteStops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TruckId");

                            b1.OwnsOne("Freight.Domain.ValueObjects.GeoLocation", "Location", b2 =>
                                {
                                    b2.Property<Guid>("StopId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("Latitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LocationLatitude");

                                    b2.Property<double>("Longitude")
                                        .HasColumnType("double precision")
                                        .HasColumnName("LocationLongitude");

                                    b2.HasKey("StopId");

                                    b2.ToTable("TruckRouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId");
                                });

                            b1.OwnsOne("Freight.Domain.ValueObjects.Capacity", "ShipmentLoad", b2 =>
                                {
                                    b2.Property<Guid>("StopId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("VolumeCubicMeters")
                                        .HasColumnType("double precision")
                                        .HasColumnName("ShipmentLoadVolumeCubicMeters");

                                    b2.Property<double>("WeightKg")
                                        .HasColumnType("double precision")
                                        .HasColumnName("ShipmentLoadWeightKg");

                                    b2.HasKey("StopId");

                                    b2.ToTable("TruckRouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId");
                                });

                            b1.Navigation("Location")
                                .IsRequired();

                            b1.Navigation("ShipmentLoad");
                        });

                    b.OwnsOne("Freight.Domain.Tracking.RouteProgress", "CurrentProgress", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<double>("CurrentDistanceKm")
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentProgress_CurrentDistanceKm");

                            b1.Property<double>("TotalDistanceKm")
                                .HasColumnType("double precision")
                                .HasColumnName("CurrentProgress_TotalDistanceKm");

                            b1.Property<int>("TotalTimeTick")
                                .HasColumnType("integer")
                                .HasColumnName("CurrentProgress_TotalTimeTick");

                            b1.HasKey("TruckId");

                            b1.ToTable("TruckRouteProgresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TruckId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.TruckCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.HasKey("TruckId");

                            b1.ToTable("Trucks");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");

                            b1.OwnsOne("Freight.Domain.ValueObjects.Capacity", "Total", b2 =>
                                {
                                    b2.Property<Guid>("TruckCapacityTruckId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("VolumeCubicMeters")
                                        .HasColumnType("double precision")
                                        .HasColumnName("TotalCapacityVolumeCubicMeters");

                                    b2.Property<double>("WeightKg")
                                        .HasColumnType("double precision")
                                        .HasColumnName("TotalCapacityWeightKg");

                                    b2.HasKey("TruckCapacityTruckId");

                                    b2.ToTable("Trucks");

                                    b2.WithOwner()
                                        .HasForeignKey("TruckCapacityTruckId");
                                });

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("CurrentProgress");

                    b.Navigation("DriverAssignment");

                    b.Navigation("Stops");
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.OwnsOne("Freight.Domain.ValueObjects.GeoLocation", "OfficeLocation", b1 =>
                        {
                            b1.Property<Guid>("TruckingCompanyId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OfficeLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OfficeLongitude");

                            b1.HasKey("TruckingCompanyId");

                            b1.ToTable("TruckingCompanies");

                            b1.WithOwner()
                                .HasForeignKey("TruckingCompanyId");
                        });

                    b.Navigation("OfficeLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipment", b =>
                {
                    b.OwnsOne("Freight.Domain.ValueObjects.GeoLocation", "DeliveryLocation", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DeliveryLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DeliveryLongitude");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.TimeWindow", "DeliveryWindow", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Earliest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeliveryWindowEarliest");

                            b1.Property<DateTime>("Latest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("DeliveryWindowLatest");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.Capacity", "Load", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("VolumeCubicMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("LoadVolumeCubicMeters");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("double precision")
                                .HasColumnName("LoadWeightKg");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.GeoLocation", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("PickupLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("PickupLongitude");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.TimeWindow", "PickupWindow", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Earliest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PickupWindowEarliest");

                            b1.Property<DateTime>("Latest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("PickupWindowLatest");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.TimeWindow", "ScheduledDeliveryWindow", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Earliest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ScheduledDeliveryWindowEarliest");

                            b1.Property<DateTime>("Latest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ScheduledDeliveryWindowLatest");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.TimeWindow", "ScheduledPickupWindow", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("Earliest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ScheduledPickupWindowEarliest");

                            b1.Property<DateTime>("Latest")
                                .HasColumnType("timestamp with time zone")
                                .HasColumnName("ScheduledPickupWindowLatest");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("DeliveryLocation")
                        .IsRequired();

                    b.Navigation("DeliveryWindow")
                        .IsRequired();

                    b.Navigation("Load")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();

                    b.Navigation("PickupWindow")
                        .IsRequired();

                    b.Navigation("ScheduledDeliveryWindow");

                    b.Navigation("ScheduledPickupWindow");
                });
#pragma warning restore 612, 618
        }
    }
}
