// <auto-generated />
using System;
using Freight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreightDbContext))]
    [Migration("20260818200613_RemoveTruckingCompanyTruckOwnership")]
    partial class RemoveTruckingCompanyTruckOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TruckingCompanies", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shippers", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.OwnsOne("Freight.Domain.ValueObjects.GeoLocation", "OfficeLocation", b1 =>
                        {
                            b1.Property<Guid>("TruckingCompanyId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OfficeLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OfficeLongitude");

                            b1.HasKey("TruckingCompanyId");

                            b1.ToTable("TruckingCompanies");

                            b1.WithOwner()
                                .HasForeignKey("TruckingCompanyId");
                        });

                    b.Navigation("OfficeLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
