// <auto-generated />
using System;
using Freight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreightDbContext))]
    [Migration("20260816214249_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freight.Domain.Fleet.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drivers");
                });

            modelBuilder.Entity("Freight.Domain.Fleet.DriverAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConfigurationType")
                        .HasColumnType("integer");

                    b.Property<Guid>("PrimaryDriverId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SecondaryDriverId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrimaryDriverId");

                    b.HasIndex("SecondaryDriverId");

                    b.ToTable("DriverAssignment");
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TruckingCompanies");
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CargoKind")
                        .HasColumnType("integer");

                    b.Property<Guid>("ShipperId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ShipperId");

                    b.ToTable("Shipments");
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shippers");
                });

            modelBuilder.Entity("Freight.Domain.Tracking.DriverComplianceState", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<bool>("AwaitingSecondBreakBlock")
                        .HasColumnType("boolean");

                    b.Property<bool>("AwaitingSecondDailyRestBlock")
                        .HasColumnType("boolean");

                    b.Property<int>("ContinuousDrivingMinutesSinceBreak")
                        .HasColumnType("integer");

                    b.Property<int>("CurrentActivity")
                        .HasColumnType("integer");

                    b.Property<int>("DailyDrivingMinutesToday")
                        .HasColumnType("integer");

                    b.Property<int>("ExtendedDaysUsedThisWeek")
                        .HasColumnType("integer");

                    b.Property<bool>("IsTodayExtended")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("LastEvaluatedSimulatedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("MinutesRemainingInCurrentActivity")
                        .HasColumnType("integer");

                    b.Property<int>("ReducedDailyRestsUsedSinceWeeklyRest")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyDrivingMinutesPriorWeek")
                        .HasColumnType("integer");

                    b.Property<int>("WeeklyDrivingMinutesThisWeek")
                        .HasColumnType("integer");

                    b.HasKey("DriverId");

                    b.ToTable("DriverComplianceStates");
                });

            modelBuilder.Entity("Freight.Domain.Tracking.DriverRulePreference", b =>
                {
                    b.Property<Guid>("DriverId")
                        .HasColumnType("uuid");

                    b.Property<int>("BreakPreference")
                        .HasColumnType("integer");

                    b.Property<int>("DailyRestPreference")
                        .HasColumnType("integer");

                    b.Property<bool>("ExtendDailyDrivingWhenEligible")
                        .HasColumnType("boolean");

                    b.Property<int>("WeeklyRestPreference")
                        .HasColumnType("integer");

                    b.HasKey("DriverId");

                    b.ToTable("DriverRulePreferences");
                });

            modelBuilder.Entity("Freight.Domain.Tracking.RouteLeg", b =>
                {
                    b.Property<Guid>("TruckId")
                        .HasColumnType("uuid");

                    b.Property<int>("LegIndex")
                        .HasColumnType("integer");

                    b.Property<int>("DurationTicks")
                        .HasColumnType("integer");

                    b.HasKey("TruckId", "LegIndex");

                    b.ToTable("RouteLegs");
                });

            modelBuilder.Entity("Freight.Domain.Tracking.RouteProgress", b =>
                {
                    b.Property<Guid>("TruckId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentLegIndex")
                        .HasColumnType("integer");

                    b.Property<int>("TicksElapsedInCurrentLeg")
                        .HasColumnType("integer");

                    b.HasKey("TruckId");

                    b.ToTable("RouteProgresses");
                });

            modelBuilder.Entity("Freight.Domain.Fleet.DriverAssignment", b =>
                {
                    b.HasOne("Freight.Domain.Fleet.Driver", "PrimaryDriver")
                        .WithMany()
                        .HasForeignKey("PrimaryDriverId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Freight.Domain.Fleet.Driver", "SecondaryDriver")
                        .WithMany()
                        .HasForeignKey("SecondaryDriverId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("PrimaryDriver");

                    b.Navigation("SecondaryDriver");
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.OwnsMany("Freight.Domain.Fleet.Truck", "Trucks", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<Guid>("DriverAssignmentId")
                                .HasColumnType("uuid");

                            b1.Property<bool>("HazmatCertified")
                                .HasColumnType("boolean");

                            b1.Property<int>("MovementState")
                                .HasColumnType("integer");

                            b1.Property<int>("TruckType")
                                .HasColumnType("integer");

                            b1.Property<Guid>("TruckingCompanyId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("DriverAssignmentId")
                                .IsUnique();

                            b1.HasIndex("TruckingCompanyId");

                            b1.ToTable("Truck");

                            b1.HasOne("Freight.Domain.Fleet.DriverAssignment", "DriverAssignment")
                                .WithOne()
                                .HasForeignKey("Freight.Domain.Fleet.TruckingCompany.Trucks#Freight.Domain.Fleet.Truck", "DriverAssignmentId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.WithOwner()
                                .HasForeignKey("TruckingCompanyId");

                            b1.OwnsMany("Freight.Domain.Fleet.Stop", "RouteStops", b2 =>
                                {
                                    b2.Property<Guid>("TruckId")
                                        .HasColumnType("uuid");

                                    b2.Property<int>("Ordinal")
                                        .HasColumnType("integer");

                                    b2.Property<int>("Kind")
                                        .HasColumnType("integer");

                                    b2.Property<Guid>("ShipmentId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("TruckId", "Ordinal");

                                    b2.ToTable("Stop");

                                    b2.WithOwner()
                                        .HasForeignKey("TruckId");
                                });

                            b1.OwnsOne("Freight.Domain.ValueObjects.TruckCapacity", "Capacity", b2 =>
                                {
                                    b2.Property<Guid>("TruckId")
                                        .HasColumnType("uuid");

                                    b2.HasKey("TruckId");

                                    b2.ToTable("Truck");

                                    b2.WithOwner()
                                        .HasForeignKey("TruckId");

                                    b2.OwnsOne("Freight.Domain.ValueObjects.Capacity", "Remaining", b3 =>
                                        {
                                            b3.Property<Guid>("TruckCapacityTruckId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("VolumeCubicMeters")
                                                .HasColumnType("double precision")
                                                .HasColumnName("RemainingVolumeCubicMeters");

                                            b3.Property<double>("WeightKg")
                                                .HasColumnType("double precision")
                                                .HasColumnName("RemainingWeightKg");

                                            b3.HasKey("TruckCapacityTruckId");

                                            b3.ToTable("Truck");

                                            b3.WithOwner()
                                                .HasForeignKey("TruckCapacityTruckId");
                                        });

                                    b2.OwnsOne("Freight.Domain.ValueObjects.Capacity", "Total", b3 =>
                                        {
                                            b3.Property<Guid>("TruckCapacityTruckId")
                                                .HasColumnType("uuid");

                                            b3.Property<double>("VolumeCubicMeters")
                                                .HasColumnType("double precision")
                                                .HasColumnName("TotalVolumeCubicMeters");

                                            b3.Property<double>("WeightKg")
                                                .HasColumnType("double precision")
                                                .HasColumnName("TotalWeightKg");

                                            b3.HasKey("TruckCapacityTruckId");

                                            b3.ToTable("Truck");

                                            b3.WithOwner()
                                                .HasForeignKey("TruckCapacityTruckId");
                                        });

                                    b2.Navigation("Remaining")
                                        .IsRequired();

                                    b2.Navigation("Total")
                                        .IsRequired();
                                });

                            b1.Navigation("Capacity")
                                .IsRequired();

                            b1.Navigation("DriverAssignment");

                            b1.Navigation("RouteStops");
                        });

                    b.Navigation("Trucks");
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipment", b =>
                {
                    b.HasOne("Freight.Domain.Shipment.Shipper", null)
                        .WithMany()
                        .HasForeignKey("ShipperId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.OwnsOne("Freight.Domain.ValueObjects.Capacity", "CargoSize", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("VolumeCubicMeters")
                                .HasColumnType("double precision")
                                .HasColumnName("VolumeCubicMeters");

                            b1.Property<double>("WeightKg")
                                .HasColumnType("double precision")
                                .HasColumnName("WeightKg");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.GeoCoordinate", "DeliveryLocation", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DeliveryLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("DeliveryLongitude");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.GeoCoordinate", "PickupLocation", b1 =>
                        {
                            b1.Property<Guid>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("PickupLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("PickupLongitude");

                            b1.HasKey("ShipmentId");

                            b1.ToTable("Shipments");

                            b1.WithOwner()
                                .HasForeignKey("ShipmentId");
                        });

                    b.Navigation("CargoSize")
                        .IsRequired();

                    b.Navigation("DeliveryLocation")
                        .IsRequired();

                    b.Navigation("PickupLocation")
                        .IsRequired();
                });

            modelBuilder.Entity("Freight.Domain.Tracking.DriverComplianceState", b =>
                {
                    b.HasOne("Freight.Domain.Fleet.Driver", null)
                        .WithOne()
                        .HasForeignKey("Freight.Domain.Tracking.DriverComplianceState", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Freight.Domain.Tracking.DriverRulePreference", b =>
                {
                    b.HasOne("Freight.Domain.Fleet.Driver", null)
                        .WithOne()
                        .HasForeignKey("Freight.Domain.Tracking.DriverRulePreference", "DriverId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
