// <auto-generated />
using System;
using Freight.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Freight.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(FreightDbContext))]
    [Migration("20260818213614_ReconcileFleetDomain")]
    partial class ReconcileFleetDomain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Freight.Domain.Fleet.Driver", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Drivers", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.Truck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("HazmatCertified")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("TruckName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TruckSize")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TruckType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid?>("TruckingCompanyId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.ToTable("Trucks", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TruckingCompanies", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Shipment.Shipper", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ContactEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Shippers", (string)null);
                });

            modelBuilder.Entity("Freight.Domain.Fleet.Driver", b =>
                {
                    b.OwnsOne("Freight.Domain.ValueObjects.DrivingRules", "Rules", b1 =>
                        {
                            b1.Property<Guid>("DriverId")
                                .HasColumnType("uuid");

                            b1.Property<string>("BreakRule")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("BreakRule");

                            b1.Property<string>("DailyRestRule")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DailyRestRule");

                            b1.Property<bool>("ExtendDailyDrivingWhenEligible")
                                .HasColumnType("boolean")
                                .HasColumnName("ExtendDailyDrivingWhenEligible");

                            b1.Property<string>("WeeklyRestRule")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("WeeklyRestRule");

                            b1.HasKey("DriverId");

                            b1.ToTable("Drivers");

                            b1.WithOwner()
                                .HasForeignKey("DriverId");
                        });

                    b.Navigation("Rules")
                        .IsRequired();
                });

            modelBuilder.Entity("Freight.Domain.Fleet.Truck", b =>
                {
                    b.OwnsOne("Freight.Domain.Fleet.DriverAssignment", "DriverAssignment", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("ActiveDriverId")
                                .HasColumnType("uuid")
                                .HasColumnName("ActiveDriverId");

                            b1.Property<string>("ConfigurationType")
                                .IsRequired()
                                .HasColumnType("text")
                                .HasColumnName("DriverConfigurationType");

                            b1.Property<Guid>("PrimaryDriverId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("SecondaryDriverId")
                                .HasColumnType("uuid");

                            b1.HasKey("TruckId");

                            b1.HasIndex("PrimaryDriverId");

                            b1.HasIndex("SecondaryDriverId");

                            b1.ToTable("Trucks");

                            b1.HasOne("Freight.Domain.Fleet.Driver", "PrimaryDriver")
                                .WithMany()
                                .HasForeignKey("PrimaryDriverId")
                                .OnDelete(DeleteBehavior.Restrict)
                                .IsRequired();

                            b1.HasOne("Freight.Domain.Fleet.Driver", "SecondaryDriver")
                                .WithMany()
                                .HasForeignKey("SecondaryDriverId")
                                .OnDelete(DeleteBehavior.Restrict);

                            b1.WithOwner()
                                .HasForeignKey("TruckId");

                            b1.Navigation("PrimaryDriver");

                            b1.Navigation("SecondaryDriver");
                        });

                    b.OwnsMany("Freight.Domain.Fleet.Stop", "RouteStops", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("uuid");

                            b1.Property<DateTime>("ExpectedArrivalTime")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<string>("Kind")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<Guid?>("ShipmentId")
                                .HasColumnType("uuid");

                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.Property<Guid?>("TruckingCompanyId")
                                .HasColumnType("uuid");

                            b1.HasKey("Id");

                            b1.HasIndex("TruckId");

                            b1.ToTable("TruckRouteStops", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("TruckId");

                            b1.OwnsOne("Freight.Domain.ValueObjects.Capacity", "ShipmentLoad", b2 =>
                                {
                                    b2.Property<Guid>("StopId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("VolumeCubicMeters")
                                        .HasColumnType("double precision")
                                        .HasColumnName("ShipmentLoadVolumeCubicMeters");

                                    b2.Property<double>("WeightKg")
                                        .HasColumnType("double precision")
                                        .HasColumnName("ShipmentLoadWeightKg");

                                    b2.HasKey("StopId");

                                    b2.ToTable("TruckRouteStops");

                                    b2.WithOwner()
                                        .HasForeignKey("StopId");
                                });

                            b1.Navigation("ShipmentLoad");
                        });

                    b.OwnsOne("Freight.Domain.ValueObjects.TruckCapacity", "Capacity", b1 =>
                        {
                            b1.Property<Guid>("TruckId")
                                .HasColumnType("uuid");

                            b1.HasKey("TruckId");

                            b1.ToTable("Trucks");

                            b1.WithOwner()
                                .HasForeignKey("TruckId");

                            b1.OwnsOne("Freight.Domain.ValueObjects.Capacity", "Total", b2 =>
                                {
                                    b2.Property<Guid>("TruckCapacityTruckId")
                                        .HasColumnType("uuid");

                                    b2.Property<double>("VolumeCubicMeters")
                                        .HasColumnType("double precision")
                                        .HasColumnName("TotalCapacityVolumeCubicMeters");

                                    b2.Property<double>("WeightKg")
                                        .HasColumnType("double precision")
                                        .HasColumnName("TotalCapacityWeightKg");

                                    b2.HasKey("TruckCapacityTruckId");

                                    b2.ToTable("Trucks");

                                    b2.WithOwner()
                                        .HasForeignKey("TruckCapacityTruckId");
                                });

                            b1.Navigation("Total")
                                .IsRequired();
                        });

                    b.Navigation("Capacity")
                        .IsRequired();

                    b.Navigation("DriverAssignment");

                    b.Navigation("RouteStops");
                });

            modelBuilder.Entity("Freight.Domain.Fleet.TruckingCompany", b =>
                {
                    b.OwnsOne("Freight.Domain.ValueObjects.GeoLocation", "OfficeLocation", b1 =>
                        {
                            b1.Property<Guid>("TruckingCompanyId")
                                .HasColumnType("uuid");

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OfficeLatitude");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision")
                                .HasColumnName("OfficeLongitude");

                            b1.HasKey("TruckingCompanyId");

                            b1.ToTable("TruckingCompanies");

                            b1.WithOwner()
                                .HasForeignKey("TruckingCompanyId");
                        });

                    b.Navigation("OfficeLocation")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
